cmake_minimum_required(VERSION 3.29)

include("${GAV_LINT_CONFIG}")

string(ASCII 1 GAV_OPEN_BRACKET)
string(ASCII 2 GAV_CLOSE_BRACKET)
string(ASCII 3 GAV_SEMICOLON)
string(ASCII 4 GAV_BACKSLASH)

function(gav_stop text)
    message(NOTICE "${text}")
    cmake_language(EXIT 1)
endfunction()

function(gav_relative_paths text out)
    string(REPLACE "${GAV_SOURCE_DIR}/" "" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(gav_regex_escape text out)
    string(REGEX REPLACE "([][+.*()^$?{}|\\\\])" "\\\\\\1" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(gav_split_lines text out)
    string(REPLACE "\r" "" text "${text}")
    string(REPLACE "\\" "${GAV_BACKSLASH}" text "${text}")
    string(REPLACE "[" "${GAV_OPEN_BRACKET}" text "${text}")
    string(REPLACE "]" "${GAV_CLOSE_BRACKET}" text "${text}")
    string(REPLACE ";" "${GAV_SEMICOLON}" text "${text}")
    string(REPLACE "\n" ";" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(gav_join_lines text out)
    string(REPLACE "${GAV_BACKSLASH}" "\\" text "${text}")
    string(REPLACE "${GAV_OPEN_BRACKET}" "[" text "${text}")
    string(REPLACE "${GAV_CLOSE_BRACKET}" "]" text "${text}")
    string(REPLACE "${GAV_SEMICOLON}" ";" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(gav_pinned_version package out)
    file(STRINGS "${GAV_LINT_REQUIREMENTS}" lines REGEX "^${package}==")
    if (NOT "${lines}" MATCHES "^${package}==([0-9]+(\\.[0-9]+)*)$")
        gav_stop("${package} is not pinned in ${GAV_LINT_REQUIREMENTS}.")
    endif ()
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

function(gav_cpp_tool package out)
    gav_pinned_version(${package} version)
    if (package STREQUAL "clang-format")
        set(override "${GAV_CLANG_FORMAT}")
    else ()
        set(override "${GAV_CLANG_TIDY}")
    endif ()
    if (override)
        execute_process(COMMAND "${override}" --version OUTPUT_VARIABLE output ERROR_VARIABLE output RESULT_VARIABLE result)
        if (NOT result EQUAL 0)
            gav_stop("${package}: ${override} could not be run.")
        endif ()
        set(found "an unknown version")
        if (output MATCHES "version ([0-9]+(\\.[0-9]+)*)")
            set(found "${CMAKE_MATCH_1}")
        endif ()
        if (NOT found STREQUAL version)
            gav_stop("${package}: found ${found}, need ${version} (${override}).")
        endif ()
        set(${out} "${override}" PARENT_SCOPE)
        return()
    endif ()
    find_program(GAV_UVX uvx)
    if (NOT GAV_UVX)
        gav_stop("uv is needed to run ${package} ${version}. Install it from https://docs.astral.sh/uv/ and run this again.")
    endif ()
    set(${out} "${GAV_UVX}" --quiet --from "${package}==${version}" "${package}" PARENT_SCOPE)
endfunction()

function(gav_qt_tool name path out)
    if (NOT path OR NOT EXISTS "${path}")
        gav_stop("${name} was not found in the Qt installation this build uses.")
    endif ()
    set(${out} "${path}" PARENT_SCOPE)
endfunction()

function(gav_print_version name)
    execute_process(COMMAND ${ARGN} --version OUTPUT_VARIABLE output ERROR_VARIABLE error RESULT_VARIABLE result)
    if (NOT result EQUAL 0 OR NOT output MATCHES "([0-9]+\\.[0-9]+\\.[0-9]+)")
        gav_stop("${name} could not be run.\n${error}")
    endif ()
    message(NOTICE "${name} ${CMAKE_MATCH_1}")
endfunction()

function(gav_format_cpp out_failed)
    gav_cpp_tool(clang-format clang_format)
    gav_print_version(clang-format ${clang_format})
    execute_process(
            COMMAND ${clang_format} -i "--style=file:${GAV_SOURCE_DIR}/.clang-format" ${GAV_FORMAT_CPP_FILES}
            RESULT_VARIABLE result
    )
    if (NOT result EQUAL 0)
        set(${out_failed} TRUE PARENT_SCOPE)
    endif ()
endfunction()

function(gav_check_cpp_format out_failed)
    gav_cpp_tool(clang-format clang_format)
    gav_print_version(clang-format ${clang_format})
    execute_process(
            COMMAND ${clang_format} --dry-run --Werror --ferror-limit=1 "--style=file:${GAV_SOURCE_DIR}/.clang-format" ${GAV_FORMAT_CPP_FILES}
            OUTPUT_VARIABLE output
            ERROR_VARIABLE output
            RESULT_VARIABLE result
    )
    if (result EQUAL 0)
        return()
    endif ()
    set(${out_failed} TRUE PARENT_SCOPE)
    set(marker ":[0-9]+:[0-9]+: (error|warning): code should be clang-formatted")
    string(REGEX MATCHALL "[^\n]+${marker}" matches "${output}")
    if (NOT matches)
        message(NOTICE "${output}")
        return()
    endif ()
    set(files "")
    foreach (match IN LISTS matches)
        string(REGEX REPLACE "${marker}$" "" file "${match}")
        gav_relative_paths("${file}" file)
        list(APPEND files "${file}")
    endforeach ()
    list(REMOVE_DUPLICATES files)
    foreach (file IN LISTS files)
        message(NOTICE "${file}: not formatted")
    endforeach ()
endfunction()

function(gav_format_qml write out_failed)
    gav_qt_tool(qmlformat "${GAV_QMLFORMAT}" qmlformat)
    gav_print_version(qmlformat "${qmlformat}")
    set(directory "${GAV_LINT_DIR}/qmlformat")
    file(REMOVE_RECURSE "${directory}")
    set(copies "")
    foreach (file IN LISTS GAV_LINT_QML_FILES)
        cmake_path(RELATIVE_PATH file BASE_DIRECTORY "${GAV_SOURCE_DIR}" OUTPUT_VARIABLE name)
        cmake_path(GET name PARENT_PATH subdirectory)
        file(COPY "${file}" DESTINATION "${directory}/${subdirectory}")
        list(APPEND copies "${directory}/${name}")
    endforeach ()
    execute_process(
            COMMAND "${qmlformat}" -s "${GAV_SOURCE_DIR}/.qmlformat.ini" -i ${copies}
            RESULT_VARIABLE result
    )
    if (NOT result EQUAL 0)
        file(REMOVE_RECURSE "${directory}")
        set(${out_failed} TRUE PARENT_SCOPE)
        return()
    endif ()
    foreach (file copy IN ZIP_LISTS GAV_LINT_QML_FILES copies)
        file(SHA256 "${file}" before)
        file(SHA256 "${copy}" after)
        if (before STREQUAL after)
            continue()
        endif ()
        if (write)
            file(COPY_FILE "${copy}" "${file}")
        else ()
            gav_relative_paths("${file}" name)
            message(NOTICE "${name}: not formatted")
            set(${out_failed} TRUE PARENT_SCOPE)
        endif ()
    endforeach ()
    file(REMOVE_RECURSE "${directory}")
endfunction()

function(gav_split_compile_commands)
    file(READ "${GAV_BINARY_DIR}/compile_commands.json" database)
    string(JSON count LENGTH "${database}")
    set(written "")
    set(index 0)
    while (index LESS count)
        string(JSON file GET "${database}" ${index} file)
        list(FIND GAV_TIDY_SOURCES "${file}" at)
        if (NOT at EQUAL -1 AND NOT at IN_LIST written)
            string(JSON entry GET "${database}" ${index})
            list(GET GAV_TIDY_DIRECTORIES ${at} directory)
            file(WRITE "${directory}/compile_commands.json.new" "[\n${entry}\n]\n")
            list(APPEND written ${at})
        endif ()
        math(EXPR index "${index} + 1")
    endwhile ()
    foreach (directory IN LISTS GAV_TIDY_DIRECTORIES)
        if (NOT EXISTS "${directory}/compile_commands.json.new")
            file(WRITE "${directory}/compile_commands.json.new" "[]\n")
        endif ()
        file(COPY_FILE "${directory}/compile_commands.json.new" "${directory}/compile_commands.json" ONLY_IF_DIFFERENT)
        file(REMOVE "${directory}/compile_commands.json.new")
    endforeach ()
endfunction()

function(gav_tidy_file)
    gav_cpp_tool(clang-tidy clang_tidy)
    gav_regex_escape("${GAV_SOURCE_DIR}" source)
    gav_regex_escape("${GAV_BINARY_DIR}" binary)
    execute_process(
            COMMAND ${clang_tidy} -p "${GAV_LINT_DIRECTORY}" --quiet
            "--header-filter=^${source}/" "--exclude-header-filter=^(${binary}|${source}/vcpkg-ports)/"
            "${GAV_LINT_FILE}"
            OUTPUT_VARIABLE output
            ERROR_VARIABLE output
            RESULT_VARIABLE result
    )
    if (result EQUAL 0)
        set(output "")
    else ()
        gav_relative_paths("${output}" output)
        gav_relative_paths("${GAV_LINT_FILE}" name)
        string(APPEND output "\n${name}: clang-tidy exited with ${result}\n")
    endif ()
    file(WRITE "${GAV_LINT_DIRECTORY}/findings.txt" "${output}")
endfunction()

function(gav_tidy_report out_failed)
    set(findings 0)
    set(seen "")
    set(report "")
    foreach (directory IN LISTS GAV_TIDY_DIRECTORIES)
        file(READ "${directory}/findings.txt" output)
        if (output STREQUAL "")
            continue()
        endif ()
        gav_split_lines("${output}" lines)
        set(keep TRUE)
        set(counted FALSE)
        set(exit_line "")
        foreach (line IN LISTS lines)
            if (line STREQUAL ""
                    OR line MATCHES "^[0-9]+ warnings?( and [0-9]+ errors?)? generated\\.$"
                    OR line MATCHES "^[0-9]+ warnings? treated as errors?$")
                continue()
            endif ()
            if (line MATCHES ": clang-tidy exited with [0-9]+$")
                set(exit_line "${line}")
                continue()
            endif ()
            if (line MATCHES "^[^ ].*:[0-9]+:[0-9]+: (warning|error): ")
                set(counted TRUE)
                if (line IN_LIST seen)
                    set(keep FALSE)
                else ()
                    list(APPEND seen "${line}")
                    math(EXPR findings "${findings} + 1")
                    set(keep TRUE)
                endif ()
            endif ()
            if (keep)
                string(APPEND report "${line}\n")
            endif ()
        endforeach ()
        if (NOT counted)
            math(EXPR findings "${findings} + 1")
            string(APPEND report "${exit_line}\n")
        endif ()
    endforeach ()
    if (findings EQUAL 0)
        return()
    endif ()
    gav_join_lines("${report}" report)
    message(NOTICE "${report}clang-tidy findings: ${findings}")
    set(${out_failed} TRUE PARENT_SCOPE)
endfunction()

function(gav_lint_qml out_failed)
    gav_qt_tool(qmllint "${GAV_QMLLINT}" qmllint)
    if (NOT EXISTS "${GAV_QMLLINT_ARGUMENTS}")
        gav_stop("${GAV_QMLLINT_ARGUMENTS} is missing. Build the application first.")
    endif ()
    execute_process(
            COMMAND "${qmllint}" "@${GAV_QMLLINT_ARGUMENTS}"
            WORKING_DIRECTORY "${GAV_SOURCE_DIR}"
            OUTPUT_VARIABLE output
            ERROR_VARIABLE output
            RESULT_VARIABLE result
    )
    if (result EQUAL 0)
        return()
    endif ()
    gav_relative_paths("${output}" output)
    string(REGEX MATCHALL "(^|\n)(Warning|Error): " matches "${output}")
    list(LENGTH matches findings)
    message(NOTICE "${output}qmllint findings: ${findings}")
    set(${out_failed} TRUE PARENT_SCOPE)
endfunction()

function(gav_check_marker file needle rule previous_rule message out_failed)
    file(READ "${file}" content)
    string(LENGTH "${needle}" needle_length)
    string(LENGTH "${content}" length)
    set(start 0)
    while (start LESS length)
        string(SUBSTRING "${content}" ${start} -1 tail)
        string(FIND "${tail}" "${needle}" at)
        if (at EQUAL -1)
            break()
        endif ()
        string(SUBSTRING "${tail}" ${at} -1 marker)
        math(EXPR at "${start} + ${at}")
        math(EXPR start "${at} + ${needle_length}")
        string(FIND "${marker}" "\n" end)
        string(SUBSTRING "${marker}" 0 ${end} marker)
        string(REPLACE "\r" "" marker "${marker}")

        string(SUBSTRING "${content}" 0 ${at} head)
        string(REGEX REPLACE "[^\n]" "" newlines "${head}")
        string(LENGTH "${newlines}" line)
        math(EXPR line "${line} + 1")

        set(previous "")
        string(FIND "${head}" "\n" line_start REVERSE)
        if (NOT line_start EQUAL -1)
            string(SUBSTRING "${head}" 0 ${line_start} head)
            string(FIND "${head}" "\n" previous_start REVERSE)
            math(EXPR previous_start "${previous_start} + 1")
            string(SUBSTRING "${head}" ${previous_start} -1 previous)
        endif ()

        set(valid TRUE)
        if (NOT marker MATCHES "${rule}")
            set(valid FALSE)
        endif ()
        if (previous_rule AND (NOT previous MATCHES "${previous_rule}" OR previous MATCHES "qmllint (disable|enable)|qmlformat (off|on)"))
            set(valid FALSE)
        endif ()
        if (NOT valid)
            gav_relative_paths("${file}" name)
            message(NOTICE "${name}:${line}: ${message}")
            set(${out_failed} TRUE PARENT_SCOPE)
        endif ()
    endwhile ()
endfunction()

function(gav_check_markers out_failed)
    set(comment_line "^[ \t]*//[ \t]*[^ \t\r]")
    foreach (file IN LISTS GAV_FORMAT_CPP_FILES)
        gav_check_marker("${file}" "NOLINT" "^NOLINT(NEXTLINE|BEGIN)?\\([^)]+\\):[ \t]*[^ \t]|^NOLINTEND\\([^)]+\\)" ""
                "a suppression names its check and gives a reason, as in `// NOLINT(check-name): reason`" failed)
        gav_check_marker("${file}" "clang-format off" "^clang-format off:[ \t]*[^ \t]" ""
                "a format opt-out gives a reason, as in `// clang-format off: reason`" failed)
    endforeach ()
    foreach (file IN LISTS GAV_LINT_QML_FILES)
        gav_check_marker("${file}" "qmllint disable" "^qmllint disable[ \t]+[a-zA-Z]" "${comment_line}"
                "a suppression names its category and has a comment line above it giving the reason" failed)
        gav_check_marker("${file}" "qmlformat off" "^qmlformat off" "${comment_line}"
                "a format opt-out has a comment line above it giving the reason" failed)
    endforeach ()
    if (failed)
        set(${out_failed} TRUE PARENT_SCOPE)
    endif ()
endfunction()

set(failed FALSE)
set(hint "")

if (GAV_LINT_ACTION STREQUAL "versions")
    gav_cpp_tool(clang-format clang_format)
    gav_cpp_tool(clang-tidy clang_tidy)
    gav_qt_tool(qmlformat "${GAV_QMLFORMAT}" qmlformat)
    gav_qt_tool(qmllint "${GAV_QMLLINT}" qmllint)
    gav_print_version(clang-format ${clang_format})
    gav_print_version(clang-tidy ${clang_tidy})
    gav_print_version(qmlformat "${qmlformat}")
    gav_print_version(qmllint "${qmllint}")
elseif (GAV_LINT_ACTION STREQUAL "format")
    gav_format_cpp(failed)
    gav_format_qml(TRUE failed)
elseif (GAV_LINT_ACTION STREQUAL "format-cpp")
    gav_format_cpp(failed)
elseif (GAV_LINT_ACTION STREQUAL "format-qml")
    gav_format_qml(TRUE failed)
elseif (GAV_LINT_ACTION STREQUAL "format-check")
    gav_check_cpp_format(failed)
    gav_format_qml(FALSE failed)
    set(hint "Run `just format` to fix.")
elseif (GAV_LINT_ACTION STREQUAL "compile-commands")
    gav_split_compile_commands()
elseif (GAV_LINT_ACTION STREQUAL "tidy")
    gav_tidy_file()
elseif (GAV_LINT_ACTION STREQUAL "lint-cpp")
    gav_tidy_report(failed)
    set(hint "Run `just lint-cpp` to reproduce.")
elseif (GAV_LINT_ACTION STREQUAL "lint-qml")
    gav_qt_tool(qmllint "${GAV_QMLLINT}" qmllint)
    gav_print_version(qmllint "${qmllint}")
    gav_lint_qml(failed)
    set(hint "Run `just lint-qml` to reproduce.")
elseif (GAV_LINT_ACTION STREQUAL "lint")
    gav_tidy_report(failed)
    gav_lint_qml(failed)
    gav_check_markers(failed)
    set(hint "Run `just lint` to reproduce.")
else ()
    gav_stop("Unknown action: ${GAV_LINT_ACTION}")
endif ()

if (failed)
    if (hint)
        message(NOTICE "${hint}")
    endif ()
    cmake_language(EXIT 1)
endif ()
